version: '3'

networks:
  travel-network:
    driver: bridge

services:

        travel:
#            container_name: travel
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - travel-network
            ports:
                - "9001:9000"
            volumes:
                - ./../travel:/travel:rw,cached
                - travel_log:/travel/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - maria-master
                - maria-slave-1
                - maria-slave-2
                - maria-slave-3
                - maria-slave-4

        travel1:
#            container_name: travel1
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - travel-network
            ports:
                - "9002:9000"
            volumes:
                - ./../travel:/travel:rw,cached
                - travel_log:/travel/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - maria-master
                - maria-slave-1
                - maria-slave-2
                - maria-slave-3
                - maria-slave-4

        travel2:
#            container_name: travel2
            build:
                context: ./php-fpm
                args:
                    - timezone=${TZ}
            networks:
                - travel-network
            ports:
                - "9003:9000"
            volumes:
                - ./../travel:/travel:rw,cached
                - travel_log:/travel/var/log
            env_file:
                - .env
            depends_on:
                - redis
                - memcached
                - maria-master
                - maria-slave-1
                - maria-slave-2
                - maria-slave-3
                - maria-slave-4

        nginx:
            container_name: nginx
            build:
                context: ./nginx
                args:
                    - timezone=${TZ}
            ports:
                - "81:80"
                - "443:443"
            networks:
                - travel-network
            depends_on:
                - travel
            volumes:
                - ./../travel/public:/travel/public
                - ./../travel1/public:/travel1/public
                - ./../travel2/public:/travel2/public
                - ./nginx/ssl:/etc/nginx/ssl
                - ./nginx/conf.d:/etc/nginx/conf.d
                - ./nginx/nginx_log:/var/log/nginx
                - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            env_file:
                - .env
            command: /bin/bash -c "exec nginx -g 'daemon off;'"

        redis:
            container_name: redis
            image: redis:latest
            networks:
                - travel-network

        memcached:
            container_name: memcached
            image: memcached:latest
            networks:
                - travel-network

#        db-master:
#            container_name: db-master
#            image: mysql:latest
#            env_file:
#                - ./db/master/.env.master
#            ports:
#                - "4406:3306"
#            volumes:
#                - ./db/master/master.sql:/docker-entrypoint-initdb.d/start.sql
#                - ./db/master/maria.master.cnf:/etc/mysql/conf.d/maria.master.cnf
#                - ./db/master/.data/mysql:/var/lib/mysql:rw
#            networks:
#                - travel-network

        maria-master:
            container_name: maria_master
            image: mariadb:latest
            env_file:
                - ./db/master/.env.master
            volumes:
                - ./db/master/master.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/master/maria.master.cnf:/etc/mysql/conf.d/maria.master.cnf
                - ./db/master/.data/mysql:/var/lib/mysql:rw
            ports:
                - "3305:3306"
            networks:
                - travel-network

        maria-slave-1:
                container_name: maria_slave_1
                image: mariadb:latest
                env_file:
                    - ./db/slaves/email/.env.slave
                volumes:
                    - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                    - ./db/slaves/email/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
                    - ./db/slaves/email/.data/mysql:/var/lib/mysql:rw
                ports:
                    - "3307:3306"
                networks:
                    - travel-network

        maria-slave-2:
                container_name: maria_slave_2
                image: mariadb:latest
                env_file:
                    - ./db/slaves/sms/.env.slave
                volumes:
                    - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                    - ./db/slaves/sms/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
                    - ./db/slaves/sms/.data/mysql:/var/lib/mysql:rw
                ports:
                    - "3308:3306"
                networks:
                    - travel-network

        maria-slave-3:
            container_name: maria_slave_3
            image: mariadb:latest
            env_file:
                - ./db/slaves/push/.env.slave
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/push/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
                - ./db/slaves/push/.data/mysql:/var/lib/mysql:rw
            ports:
                - "3309:3306"
            networks:
                - travel-network

        maria-slave-4:
            container_name: maria_slave_4
            image: mariadb:latest
            env_file:
                - ./db/slaves/call/.env.slave
            volumes:
                - ./db/slaves/slave.sql:/docker-entrypoint-initdb.d/start.sql
                - ./db/slaves/call/maria.slave.cnf:/etc/mysql/conf.d/maria.slave.cnf
                - ./db/slaves/call/.data/mysql:/var/lib/mysql:rw
            ports:
                - "3310:3306"
            networks:
                - travel-network
volumes:
    nginx_log:
    travel_log:
    db:
        driver: local

